;MODO DE DIRECCIONAMIENTO RELATIVO
;DE 16 Y 8 BITS
;ejemplo para revisar la practica
XSUNO	EQU	%110000
	ORG	@27
SDOS	EQU	@120
SXYZ	EQU	$003
	BLO	SUNO
	LBLO	SDOS
;DIFERENTES INSTRUCCIONES
	BVC	SUNO
	LBVC	STRES
STRES	BSR	SDOS
	END